name: My First Workflow 
on: push
jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v5
        - name: Multiline script execution
          run: |
            echo "My first github account job"
            ls -lart
            cat README.md
        
        - name: Generate ASCII key art
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt