name: My First Workflow 
on: push
jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v5
        - name: Welcome Message
          run: echo "My first github account job"

        - name: List Files
          run: ls

        - name: Read Files
          run: cat README.md