name: Generate ASCII art
on: push
jobs:
     ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v5

        - name: list repo files
          run: ls -lart

        - name: Executing ascii script
          run: |
            chmod 755 ascii-script.sh
            ./ascii-script.sh
