name: matric configuration
on: push
jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                os: [ ubuntu-latest, ubuntu-20.04, window-latest ]
                images: [hello-world, alpine]
                exclude:
                    - os: window-latest
                      images: alpine
                include: 
                    - os: unbuntu-20.04
                      images: amd64/alpine
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo docker details
          run: docker info

        - name: Run Image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}