name: workflow filter and activities
on:
    push:     #events added
        branches:
            - main
            - '!feature/*'
    pull_request:
        types: 
            - opened
            - closed
        branches: 
            - main
        paths-ignore: 
            - README.md 

jobs: 
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: workflow execution
          run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}